---
- name: init a new ansible controlled project
  hosts: localhost
  connection: local
  collections:
    - ansible.builtin
  gather_facts: no
  become: no
  vars:
    project_root_dir: "{{ lookup('env', 'PWD') }}"
    project_inventory_path: "env/hosts/minimal.yml"
    project_tmp_dir: "/tmp"
    project_ssh_user_key_file: ubuntu_ed25519
    project_ssh_key_path: "env/ssh/keys"
  tasks:

    - name: file | various directories should be present
      file:
        path: "{{ project_root_dir }}/env/{{ item }}"
        state: directory
      loop:
        - ssh
        - ssh/keys
        - ssh/sockets
        - hosts

    - name: openssh_keypair | '{{ project_root_dir }}/{{ project_ssh_key_path }}/{{ project_ssh_user_key_file }}' should be present
      openssh_keypair:
        path: "{{ project_root_dir }}/{{ project_ssh_key_path }}/{{ project_ssh_user_key_file }}"
        owner: "{{ ansible_user }}"
        state: present
        comment: ""
        type: ed25519
        mode: 0600

        
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#ansible-collections-ansible-builtin-template-module
    - name: ansible.cfg file should be present
      ansible.builtin.template:
        src: "{{ project_root_dir }}/templates/ansible.cfg.j2"
        dest: "/home/ansible/formation/ansible.cfg"
    
    # # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/stat_module.html
    # - stat:
    #     path: "{{ project_root_dir }}/{{ project_ssh_key_path }}/{{ project_ssh_user_key_file }}"
    #   register: p

    # - name: debug | project root dir
    #   debug:
    #     msg: "{{ project_root_dir }} {{ ansible_user }}"

    # - debug:
    #     msg: "{{ p.stat }}"
      
    # - debug:
    #     msg: "{{ p.stat.isreg }} {{ ansible_user }}"
    #   when: p.stat.isreg is defined
